export const experienceSectionData = [
    {
        companyName: "HelloScribe A.I",
        companyLocation: "Florida, USA",
        companyUrl: "https://helloscribe.ai",
        companySummary:
            "Focused on building and designing innovative features by leveraging AI technologies to simplify and enhance productivity.",
        position: "Co-Founder & Lead Software Engineer",
        from: "Feb 2024",
        till: "Present",
        current: true,
        jobType: "Remote",
        employmentType: "Full-time",
        description: [
            "Led the newly formed remote team as the company transitioned from MVP to the production phase and acquired 3000+ new users",
            "Built a metered billing system in 7 weeks that made subscriptions more flexible and 50% cheaper",
            "Reduced the login/registration defect rate to 0% and improved the security by rewriting all the Auth modules in 2 weeks",
            "Architected a performant and flexible data processing pipelines that can handle up to 1,000 concurrent requests by utilizing Python’s async and concurrency",
            "Improved debugging velocity by implementing detailed logging in the production apps",
        ],
        techStack: [
            "Python",
            "JavaScript",
            "Node.js",
            "Express.js",
            "Vue.js",
            "MongoDB",
        ],
    },
    {
        companyName: "X-Booker",
        companyLocation: "Chessington, UK",
        companyUrl: "https://x-booker.co.uk",
        companySummary:
            "Building the next generation integrations to simplify the lead acquisition and adminstration tasks.",
        position: "Lead Full-Stack Engineer",
        from: "Apr 2022",
        till: "Feb 2024",
        current: false,
        jobType: "Remote",
        employmentType: "Contract",
        description: [
            "Mentored and assisted junior developers, in understanding the platform, and developing new features",
            "Architected a Tired per-user subscription system with buyable perks using Stripe",
            "Developed a pub-sub solution using Node.js (TypeScript) and Firestore that performs a set of automated tasks in the background while keeping the main thread open to serve clients",
            "Built a secured API key-based third-party integration for the X-Booker API",
            "Built a CI/CD pipeline to auto-deploy two versions (Production & Staging) of the system on K8s",
        ],
        techStack: [
            "TypeScript",
            "Python",
            "Node.js",
            "Next.js",
            "GCP",
            "Docker",
            "Redis",
            "Kubernetes",
        ],
    },
];
