name: CI/CD

on:
  push:
    branches:
      - main

env:
  VERSION: 1.1.0
  VITE_SERVER_URL: https://sifatulrabbi.com

jobs:
  deploy-on-hosting-server:
    name: Deploy on hosting server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun 1.3.1
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1
      - name: Install dependencies
        run: bun install

      - name: Build React app
        run: bun build

      - name: Deploy on hosting server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: 22
          key: ${{ secrets.SSH_SECRET_KEY }}
          username: root
          source: dist
          target: /var/www/portfolio
          overwrite: true
